### ISSUE TITLE
Levoit Core 300s Luftfilter bitte implementieren

### ISSUE THREAD

**Issue by jenskaschub** [TA2k/ioBroker.vesync#1]
Hallo, 
super dass es endlich einen Adapter gibt, Danke schonmal dafür.
Der o.g. Luftfilter ist noch nicht steuerbar, bzw. die Werte passen nicht. 

An-Ausschalten geht, aber das war's dann auch schon.
Ich weiss nicht ob es Dir hilft wenn ich das Gerät mit Dir teile (Feature in der ANdroid App) oder ob Du die ZUgangsdaten brauchst...

**Comment by TA2k** [comment]
gerne das gerät mit mir teilen
tombox2020@gmail.com

**Comment by jenskaschub** [comment]
Habe das Gerät über die App geteilt...

**Comment by TA2k** [comment]
Habe reingeschaut. alle werte die die app hat werden unter status ausgegeben
Steuern geht anscheinend setSwitch was auch funktioniert

**Comment by jenskaschub** [comment]
An-Aus geht (setswitch), aber nicht

-auto/manuel
-Ventilatorstufe niedrig/mittel/hoch/Schlaf
-Kindersicherung
-Display an/aus

Die Dinge erscheinen im Remote Pfad gar nicht, dafür setTargetHumidty, was das Gerät gar nicht hat

**Comment by jenskaschub** [comment]
Status wird auch nicht aktualisiert:
- mode
- level
- display

**Comment by TA2k** [comment]
Habe ich mal in die GitHub version eingefügt

**Comment by TA2k** [comment]
Habe ich mal in die GitHub version eingefügt
