### ISSUE TITLE
Invalid Account data does not throw an error in log

### ISSUE THREAD

**Issue by Grizzelbee** [TA2k/ioBroker.vesync#2]
**Describe the bug**  
Just installed the adapter and misspelled my email address, wich resulted in this return information from the API:

```
vesync.0 | 2022-12-19 11:13:07.106 | info | terminating
-- | -- | -- | --
vesync.0 | 2022-12-19 11:13:07.104 | info | Got terminate signal TERMINATE_YOURSELF
vesync.0 | 2022-12-19 11:12:03.157 | debug | {"traceId":"","code":-11202022,"msg":"the account does not exist","module":null,"stacktrace":null,"result":null}
vesync.0 | 2022-12-19 11:12:02.600 | info | Login to VeSync
vesync.0 | 2022-12-19 11:12:02.582 | info | starting.  Version 0.0.2 (non-npm:  TA2k/ioBroker.vesync#975612d4c62858b1344d2ca8bf15ad91e00c4ff4) in  /opt/iobroker/node_modules/iobroker.vesync, node: v16.18.1,  js-controller: 4.0.23
```
but the log does not inform about this error. It's just telling: "Login to VeSync" to eternity.

**To Reproduce**  
1. Go to admin
2. enter an non existing account
3. start the adapter
4. See >>nothing<<

**Expected behavior**  
A clear and concise error message saying what has happend

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: currrent from github (saying 0.0.2)
 - JS-Controller version: 4.0.23 
 - Node version: 16.18.1 
 - Operating system: debian linux

**Comment by TA2k** [comment]
Added error
